# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-17 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField()),
                ('time_created', models.DateTimeField()),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotifyMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertitle', models.CharField(max_length=50)),
                ('userdetail', models.CharField(max_length=500)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotifyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='notifymap',
            name='nottype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.NotifyType'),
        ),
        migrations.AddField(
            model_name='notification',
            name='nottype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.NotifyType'),
        ),
    ]
