# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-17 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ack_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
