# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-18 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0003_auto_20170818_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifymap',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
