# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-18 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0004_auto_20170818_1504'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notifymap',
            unique_together=set([('deployment', 'nottype')]),
        ),
    ]
