# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 06:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('acttimestamp', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Activity')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgitationSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('level', models.IntegerField()),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverDailySurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverEmotionSubsurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Isolated', models.BooleanField(default=False)),
                ('Exhausted', models.BooleanField(default=False)),
                ('Worried', models.BooleanField(default=False)),
                ('Frustrated', models.BooleanField(default=False)),
                ('Discouraged', models.BooleanField(default=False)),
                ('Rested', models.BooleanField(default=False)),
                ('Busy', models.BooleanField(default=False)),
                ('HangingInThere', models.BooleanField(default=False)),
                ('Okay', models.BooleanField(default=False)),
                ('Calm', models.BooleanField(default=False)),
                ('Satisfied', models.BooleanField(default=False)),
                ('Hopeful', models.BooleanField(default=False)),
                ('Motivated', models.BooleanField(default=False)),
                ('Confident', models.BooleanField(default=False)),
                ('InControl', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionSubsurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SadVoice', models.BooleanField(default=False)),
                ('Tearfulness', models.BooleanField(default=False)),
                ('LackReactionToPleasantEvents', models.BooleanField(default=False)),
                ('VeryWorried', models.BooleanField(default=False)),
                ('Frightened', models.BooleanField(default=False)),
                ('TalkLess', models.BooleanField(default=False)),
                ('AppetiteLoss', models.BooleanField(default=False)),
                ('LessInterestInHobbies', models.BooleanField(default=False)),
                ('SadExpression', models.BooleanField(default=False)),
                ('LackOfInterest', models.BooleanField(default=False)),
                ('TroubleConcentrating', models.BooleanField(default=False)),
                ('BotheredByUsualActivites', models.BooleanField(default=False)),
                ('SlowMovement', models.BooleanField(default=False)),
                ('SlowSpeech', models.BooleanField(default=False)),
                ('SlowReaction', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationSubsurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kicking', models.BooleanField(default=False)),
                ('Hitting', models.BooleanField(default=False)),
                ('Pacing', models.BooleanField(default=False)),
                ('Wandering', models.BooleanField(default=False)),
                ('Disrobing', models.BooleanField(default=False)),
                ('Scratching', models.BooleanField(default=False)),
                ('ScreamingYelling', models.BooleanField(default=False)),
                ('StrangeNoises', models.BooleanField(default=False)),
                ('Repetitve', models.BooleanField(default=False)),
                ('Biting', models.BooleanField(default=False)),
                ('Spitting', models.BooleanField(default=False)),
                ('EatingNonFood', models.BooleanField(default=False)),
                ('BreakingThings', models.BooleanField(default=False)),
                ('UnableToFindCommonPlaces', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SleepSubsurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MultipleBathroomVisits', models.BooleanField(default=False)),
                ('DifficultyFallingAsleep', models.BooleanField(default=False)),
                ('BadDreams', models.BooleanField(default=False)),
                ('WakeUpFrequently', models.BooleanField(default=False)),
                ('WakeUpEarly', models.BooleanField(default=False)),
                ('MoreNaps', models.BooleanField(default=False)),
                ('RestlessOveractive', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='caregiverdailysurvey',
            name='PWDEmotions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PWDEmotionSubsurvey', to='survey.EmotionSubsurvey'),
        ),
        migrations.AddField(
            model_name='caregiverdailysurvey',
            name='PWDSleepEvents',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PWDSleepSubsurvey', to='survey.SleepSubsurvey'),
        ),
        migrations.AddField(
            model_name='caregiverdailysurvey',
            name='caregiverEmotions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.CaregiverEmotionSubsurvey'),
        ),
        migrations.AddField(
            model_name='caregiverdailysurvey',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agitationsurvey',
            name='observations',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.ObservationSubsurvey'),
        ),
    ]
