# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observationsubsurvey',
            old_name='Repetitve',
            new_name='Repetitive',
        ),
    ]
