# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20160224_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='agitationsurvey',
            name='PWDEmotions',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.EmotionSubsurvey'),
            preserve_default=False,
        ),
    ]
