# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_agitationsurvey_pwdemotions'),
        ('survey', '0004_agitationsurvey_agitimestamp'),
    ]

    operations = [
    ]
