# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0005_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityBundleMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Activity')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_member', to='survey.ActivityBundle')),
            ],
        ),
        migrations.RemoveField(
            model_name='activityreport',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activityreport',
            name='deployment',
        ),
        migrations.DeleteModel(
            name='ActivityReport',
        ),
    ]
