# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_activitybundlemember_deployment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionsubsurvey',
            name='BotheredByUsualActivites',
        ),
        migrations.RemoveField(
            model_name='emotionsubsurvey',
            name='LackOfInterest',
        ),
        migrations.RemoveField(
            model_name='emotionsubsurvey',
            name='LessInterestInHobbies',
        ),
        migrations.RemoveField(
            model_name='emotionsubsurvey',
            name='SadVoice',
        ),
        migrations.RemoveField(
            model_name='emotionsubsurvey',
            name='SlowMovement',
        ),
        migrations.RemoveField(
            model_name='emotionsubsurvey',
            name='TroubleConcentrating',
        ),
        migrations.RemoveField(
            model_name='emotionsubsurvey',
            name='VeryWorried',
        ),
        migrations.AddField(
            model_name='emotionsubsurvey',
            name='AnticipationOfWorst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotionsubsurvey',
            name='LackEnergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotionsubsurvey',
            name='LossInterestInUsualActivities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotionsubsurvey',
            name='LowSelfEsteem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotionsubsurvey',
            name='Physical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotionsubsurvey',
            name='ShortTemper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotionsubsurvey',
            name='Sucididal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotionsubsurvey',
            name='TroublePayingAttention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotionsubsurvey',
            name='Worrying',
            field=models.BooleanField(default=False),
        ),
    ]
