# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20160318_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotionsubsurvey',
            old_name='Sucididal',
            new_name='Suicidal',
        ),
    ]
