# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-09 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_remove_agitationsurvey_pwdemotions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observationsubsurvey',
            old_name='Pacing',
            new_name='Ambulating',
        ),
        migrations.RenameField(
            model_name='observationsubsurvey',
            old_name='Disrobing',
            new_name='Clothing',
        ),
        migrations.RenameField(
            model_name='observationsubsurvey',
            old_name='StrangeNoises',
            new_name='Communication',
        ),
        migrations.RenameField(
            model_name='observationsubsurvey',
            old_name='UnableToFindCommonPlaces',
            new_name='Lost',
        ),
        migrations.RenameField(
            model_name='observationsubsurvey',
            old_name='EatingNonFood',
            new_name='OralFixation',
        ),
        migrations.RenameField(
            model_name='observationsubsurvey',
            old_name='Hitting',
            new_name='Physical1',
        ),
        migrations.RenameField(
            model_name='observationsubsurvey',
            old_name='Biting',
            new_name='Physical2',
        ),
        migrations.RenameField(
            model_name='observationsubsurvey',
            old_name='Repetitive',
            new_name='Repetition',
        ),
        migrations.RenameField(
            model_name='observationsubsurvey',
            old_name='ScreamingYelling',
            new_name='Vocal2',
        ),
        migrations.RemoveField(
            model_name='observationsubsurvey',
            name='BreakingThings',
        ),
        migrations.RemoveField(
            model_name='observationsubsurvey',
            name='Kicking',
        ),
        migrations.RemoveField(
            model_name='observationsubsurvey',
            name='Scratching',
        ),
        migrations.RemoveField(
            model_name='observationsubsurvey',
            name='Spitting',
        ),
        migrations.RemoveField(
            model_name='observationsubsurvey',
            name='Wandering',
        ),
        migrations.AddField(
            model_name='observationsubsurvey',
            name='Annoying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observationsubsurvey',
            name='Restlessness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observationsubsurvey',
            name='Shadowing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observationsubsurvey',
            name='Touching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observationsubsurvey',
            name='Vocal1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observationsubsurvey',
            name='Withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
