# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20160909_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observationsubsurvey',
            old_name='Ambulating',
            new_name='Ambulation',
        ),
        migrations.RenameField(
            model_name='observationsubsurvey',
            old_name='Restlessness',
            new_name='Frustration',
        ),
        migrations.RemoveField(
            model_name='observationsubsurvey',
            name='Annoying',
        ),
    ]
