# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-06 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20161001_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='agitationsurvey',
            name='agilocation',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
