# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-06 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_agitationsurvey_agilocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agitationsurvey',
            old_name='agilocation',
            new_name='agiloc',
        ),
    ]
