# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-29 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20161206_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubsurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.BooleanField(default=False)),
                ('question2', models.BooleanField(default=False)),
                ('question3', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='agitationsurvey',
            name='notificationResponse',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='survey.NotificationSubsurvey'),
            preserve_default=False,
        ),
    ]
