# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-18 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20171029_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agitationsurvey',
            old_name='notificationResponse',
            new_name='notifications',
        ),
        migrations.RenameField(
            model_name='notificationsubsurvey',
            old_name='question1',
            new_name='Question1',
        ),
        migrations.RenameField(
            model_name='notificationsubsurvey',
            old_name='question2',
            new_name='Question2',
        ),
        migrations.RenameField(
            model_name='notificationsubsurvey',
            old_name='question3',
            new_name='Question3',
        ),
    ]
