# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-12-09 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_intervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='value',
            field=models.CharField(max_length=300),
        ),
    ]
