# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-12-09 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20181209_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='deployment',
        ),
        migrations.DeleteModel(
            name='Intervention',
        ),
    ]
