# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-12-10 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0003_interventionusagesurvey_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionusagesurvey',
            name='value1',
            field=models.CharField(default='NA', max_length=300),
        ),
        migrations.AddField(
            model_name='interventionusagesurvey',
            name='value2',
            field=models.CharField(default='NA', max_length=300),
        ),
        migrations.AddField(
            model_name='interventionusagesurvey',
            name='value3',
            field=models.CharField(default='NA', max_length=300),
        ),
        migrations.AddField(
            model_name='interventionusagesurvey',
            name='value4',
            field=models.CharField(default='NA', max_length=300),
        ),
    ]
