# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-12-10 02:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_auto_20181210_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionusagesurvey',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
